using System;
using System.Collections.Generic;
using DTCPB;

namespace DTCCommon
{
    public class MessageTypes
    {
        public static Dictionary<Type, DTCMessageType> MessageTypeByMessage = new Dictionary<Type, DTCMessageType>
        {
            {typeof(LogonRequest), DTCMessageType.LogonRequest},
            {typeof(LogonResponse), DTCMessageType.LogonResponse},
            {typeof(Heartbeat), DTCMessageType.Heartbeat},
            {typeof(Logoff), DTCMessageType.Logoff},
            {typeof(EncodingRequest), DTCMessageType.EncodingRequest},
            {typeof(EncodingResponse), DTCMessageType.EncodingResponse},
            {typeof(MarketDataRequest), DTCMessageType.MarketDataRequest},
            {typeof(MarketDataReject), DTCMessageType.MarketDataReject},
            {typeof(MarketDataSnapshot), DTCMessageType.MarketDataSnapshot},
            {typeof(MarketDataSnapshot_Int), DTCMessageType.MarketDataSnapshotInt},
            {typeof(MarketDataUpdateTrade), DTCMessageType.MarketDataUpdateTrade},
            {typeof(MarketDataUpdateTradeCompact), DTCMessageType.MarketDataUpdateTradeCompact},
            {typeof(MarketDataUpdateTrade_Int), DTCMessageType.MarketDataUpdateTradeInt},
            {typeof(MarketDataUpdateLastTradeSnapshot), DTCMessageType.MarketDataUpdateLastTradeSnapshot},
            {typeof(MarketDataUpdateBidAsk), DTCMessageType.MarketDataUpdateBidAsk},
            {typeof(MarketDataUpdateBidAskCompact), DTCMessageType.MarketDataUpdateBidAskCompact},
            {typeof(MarketDataUpdateBidAsk_Int), DTCMessageType.MarketDataUpdateBidAskInt},
            {typeof(MarketDataUpdateSessionOpen), DTCMessageType.MarketDataUpdateSessionOpen},
            {typeof(MarketDataUpdateSessionOpen_Int), DTCMessageType.MarketDataUpdateSessionOpenInt},
            {typeof(MarketDataUpdateSessionHigh), DTCMessageType.MarketDataUpdateSessionHigh},
            {typeof(MarketDataUpdateSessionHigh_Int), DTCMessageType.MarketDataUpdateSessionHighInt},
            {typeof(MarketDataUpdateSessionLow), DTCMessageType.MarketDataUpdateSessionLow},
            {typeof(MarketDataUpdateSessionLow_Int), DTCMessageType.MarketDataUpdateSessionLowInt},
            {typeof(MarketDataUpdateSessionVolume), DTCMessageType.MarketDataUpdateSessionVolume},
            {typeof(MarketDataUpdateOpenInterest), DTCMessageType.MarketDataUpdateOpenInterest},
            {typeof(MarketDataUpdateSessionSettlement), DTCMessageType.MarketDataUpdateSessionSettlement},
            {typeof(MarketDataUpdateSessionSettlement_Int), DTCMessageType.MarketDataUpdateSessionSettlementInt},
            {typeof(MarketDataUpdateSessionNumTrades), DTCMessageType.MarketDataUpdateSessionNumTrades},
            {typeof(MarketDataUpdateTradingSessionDate), DTCMessageType.MarketDataUpdateTradingSessionDate},
            {typeof(MarketDepthRequest), DTCMessageType.MarketDepthRequest},
            {typeof(MarketDepthReject), DTCMessageType.MarketDepthReject},
            {typeof(MarketDepthSnapshotLevel), DTCMessageType.MarketDepthSnapshotLevel},
            {typeof(MarketDepthSnapshotLevel_Int), DTCMessageType.MarketDepthSnapshotLevelInt},
            {typeof(MarketDepthUpdateLevel), DTCMessageType.MarketDepthUpdateLevel},
            {typeof(MarketDepthUpdateLevelCompact), DTCMessageType.MarketDepthUpdateLevelCompact},
            {typeof(MarketDepthUpdateLevel_Int), DTCMessageType.MarketDepthUpdateLevelInt},
            {typeof(MarketDepthFullUpdate10), DTCMessageType.MarketDepthFullUpdate10},
            {typeof(MarketDepthFullUpdate20), DTCMessageType.MarketDepthFullUpdate20},
            {typeof(MarketDataFeedStatus), DTCMessageType.MarketDataFeedStatus},
            {typeof(MarketDataFeedSymbolStatus), DTCMessageType.MarketDataFeedSymbolStatus},
            {typeof(SubmitNewSingleOrder), DTCMessageType.SubmitNewSingleOrder},
            {typeof(SubmitNewSingleOrderInt), DTCMessageType.SubmitNewSingleOrderInt},
            {typeof(SubmitNewOCOOrder), DTCMessageType.SubmitNewOcoOrder},
            {typeof(SubmitNewOCOOrderInt), DTCMessageType.SubmitNewOcoOrderInt},
            {typeof(CancelOrder), DTCMessageType.CancelOrder},
            {typeof(CancelReplaceOrder), DTCMessageType.CancelReplaceOrder},
            {typeof(CancelReplaceOrderInt), DTCMessageType.CancelReplaceOrderInt},
            {typeof(OpenOrdersRequest), DTCMessageType.OpenOrdersRequest},
            {typeof(OpenOrdersReject), DTCMessageType.OpenOrdersReject},
            {typeof(OrderUpdate), DTCMessageType.OrderUpdate},
            {typeof(HistoricalOrderFillsRequest), DTCMessageType.HistoricalOrderFillsRequest},
            {typeof(HistoricalOrderFillResponse), DTCMessageType.HistoricalOrderFillResponse},
            {typeof(CurrentPositionsRequest), DTCMessageType.CurrentPositionsRequest},
            {typeof(CurrentPositionsReject), DTCMessageType.CurrentPositionsReject},
            {typeof(PositionUpdate), DTCMessageType.PositionUpdate},
            {typeof(TradeAccountsRequest), DTCMessageType.TradeAccountsRequest},
            {typeof(TradeAccountResponse), DTCMessageType.TradeAccountResponse},
            {typeof(ExchangeListRequest), DTCMessageType.ExchangeListRequest},
            {typeof(ExchangeListResponse), DTCMessageType.ExchangeListResponse},
            {typeof(SymbolsForExchangeRequest), DTCMessageType.SymbolsForExchangeRequest},
            {typeof(UnderlyingSymbolsForExchangeRequest), DTCMessageType.UnderlyingSymbolsForExchangeRequest},
            {typeof(SymbolsForUnderlyingRequest), DTCMessageType.SymbolsForUnderlyingRequest},
            {typeof(SecurityDefinitionForSymbolRequest), DTCMessageType.SecurityDefinitionForSymbolRequest},
            {typeof(SecurityDefinitionResponse), DTCMessageType.SecurityDefinitionResponse},
            {typeof(SymbolSearchRequest), DTCMessageType.SymbolSearchRequest},
            {typeof(SecurityDefinitionReject), DTCMessageType.SecurityDefinitionReject},
            {typeof(AccountBalanceRequest), DTCMessageType.AccountBalanceRequest},
            {typeof(AccountBalanceReject), DTCMessageType.AccountBalanceReject},
            {typeof(AccountBalanceUpdate), DTCMessageType.AccountBalanceUpdate},
            {typeof(GeneralLogMessage), DTCMessageType.GeneralLogMessage},
            {typeof(HistoricalPriceDataRequest), DTCMessageType.HistoricalPriceDataRequest},
            {typeof(HistoricalPriceDataResponseHeader), DTCMessageType.HistoricalPriceDataResponseHeader},
            {typeof(HistoricalPriceDataReject), DTCMessageType.HistoricalPriceDataReject},
            {typeof(HistoricalPriceDataRecordResponse), DTCMessageType.HistoricalPriceDataRecordResponse},
            {typeof(HistoricalPriceDataTickRecordResponse), DTCMessageType.HistoricalPriceDataTickRecordResponse},
            {typeof(HistoricalPriceDataRecordResponse_Int), DTCMessageType.HistoricalPriceDataRecordResponseInt},
            {typeof(HistoricalPriceDataTickRecordResponse_Int), DTCMessageType.HistoricalPriceDataTickRecordResponseInt},
        };
    }
}
